### ISSUE TITLE
Numbers are not cast to the target type

### ISSUE THREAD

**Issue by geoah** [krak3n/gofig#2]
Trying to parse `{"port": 3}` onto a struct with something like `Port int` results in `could not set value of 3(int64) on field 0(int)`. Same thing will happen with other floats/ints.

Is this something that should be expected from `gofig` or would it be up to the developer to use the correct types in their config structs?

One annoying thing will be that JSON configs for floats will have to explicit decimal points in order for the unmarshaller to consider them floats. (ie `3.0` instead of `3`)

**Comment by geoah** [comment]
Hm, sorry @krak3n this was actually not the reason for that error.
The issue is actually a bit weirder.

* https://play.golang.org/p/f89D0wqxrC3 - works, no `a`
* https://play.golang.org/p/koXPMJf-Bi_3 - errors, `a` exists in both struct and body
* https://play.golang.org/p/lMsgWxzuS9F - errors, `a` exists in struct only
* https://play.golang.org/p/PeOsFN1fFrK - errors, `a` exists in json only

**Comment by krak3n** [comment]
@geoah thanks for the report.

I believe these issues have been resolved in 9bb869c included in `v0.0.1`.

The playground seems to cache the mod downloads so you may not see the correct results. Just change some of the values :stuck_out_tongue: 

Closing this, please reopen if you continue to see problems :+1:
